# Generated by Django 5.0.7 on 2024-07-30 10:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=True, populate_from="name", unique=True
            ),
        ),
    ]
