# Generated by Django 5.0.7 on 2024-07-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vapp", "0004_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customorder",
            options={},
        ),
    ]
