# Generated by Django 5.0.7 on 2024-07-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vapp", "0005_alter_customorder_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customorder",
            name="proposed_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
